# Generated by Django 4.1.2 on 2023-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage1',
            name='log_date',
        ),
        migrations.RemoveField(
            model_name='logmessage1',
            name='logger',
        ),
        migrations.RemoveField(
            model_name='logmessage1',
            name='message',
        ),
        migrations.AddField(
            model_name='logmessage1',
            name='dob',
            field=models.CharField(default='01/1/1917', max_length=10),
        ),
        migrations.AddField(
            model_name='logmessage1',
            name='firstName',
            field=models.CharField(default='firstName', max_length=100),
        ),
        migrations.AddField(
            model_name='logmessage1',
            name='lastName',
            field=models.CharField(default='lastName', max_length=100),
        ),
        migrations.AddField(
            model_name='logmessage1',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='logmessage1',
            name='repNumber',
            field=models.IntegerField(default=1),
        ),
    ]
