# Generated by Django 4.1.2 on 2023-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0002_remove_logmessage1_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage1',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='repNumber',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
