# Generated by Django 4.1.2 on 2023-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0003_alter_logmessage1_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage1',
            name='repNumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
