# Generated by Django 4.1.2 on 2023-01-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0006_logmessage2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogMessage2',
            new_name='LogMessage3',
        ),
    ]
