# Generated by Django 4.1.2 on 2023-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0007_rename_logmessage2_logmessage3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage3',
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='repNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
