# Generated by Django 4.1.2 on 2023-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0008_delete_logmessage3_alter_logmessage1_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage1',
            name='abc',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
