# Generated by Django 4.1.2 on 2023-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0009_logmessage1_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage1',
            name='abc',
            field=models.CharField(max_length=10),
        ),
    ]
