# Generated by Django 4.1.2 on 2023-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0011_remove_logmessage1_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ageRating', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('film', models.CharField(max_length=100)),
                ('filmimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='logmessage1',
            name='lastName',
            field=models.CharField(max_length=500),
        ),
    ]
