# Generated by Django 4.1.2 on 2023-01-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0012_films_post_alter_logmessage1_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='film',
        ),
    ]
