# Generated by Django 4.1.2 on 2023-01-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0013_remove_films_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='filmimage',
            new_name='filmImage',
        ),
    ]
