# Generated by Django 4.1.2 on 2023-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0014_rename_filmimage_films_filmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='filmDescription',
            field=models.CharField(default='Description', max_length=500),
        ),
    ]
