# Generated by Django 4.1.2 on 2023-01-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0015_films_filmdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='filmImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
