# Generated by Django 4.1.2 on 2023-01-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0016_alter_films_filmimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogMessage1',
            new_name='ClubRep',
        ),
    ]
