# Generated by Django 4.1.2 on 2023-01-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desd_assignment', '0017_rename_logmessage1_clubrep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
